---
version: 2
multicolumn: false
web-width: 200
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/lbhb_logo/lbhb_logo.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/164141/articles/200549/master/file/figures/lbhb_logo/lbhb_logo.png"
    folder_url: "/users/164141/articles/200549/master/folder/figures/lbhb_logo"
