---
version: 2
multicolumn: false
web-width: 500
export-width: 
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/mass/Untitled 1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/227750/articles/286813/master/folder/figures/mass"
    url: "/users/227750/articles/286813/master/file/figures/mass/Untitled%201.png"
